# Replace config values and build & publish Docker image to Docker Hub

trigger:
  branches:
    include:
    - master
    exclude:
      - '*'
  paths:
    include:
    - endpoints/*
    - Dockerfile
    - requirements.txt
    - run.py
    - devops/docker-build-pipeline.yml
    exclude:
    - '*'
  
# no PR builds
pr: none

resources:
- repo: self

variables:
  major: 0
  minor: 1
  # counter variable doc: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#counter
  # IMPORTANT: path is still a single number - the prefix is just created to reset the counter when changes occur
  patch: $[counter(format('{0}.{1}', variables['major'], variables['minor']), 1)]

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: FileTransform@1
      displayName: 'Insert credentials to config.json'
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)'
        fileType: 'json'
        targetFiles: |
          config.json
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 'docker-hub-dheinze'
        repository: 'dheinze/predict-service'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          $(major).$(minor).$(patch)
          latest
