# Replace config values and build & publish Docker image to Docker Hub

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - endpoints/*
    - Dockerfile
    - requirements.txt
    - run.py
    exclude:
    - '*'
  
# no PR builds
pr: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: FileTransform@1
      displayName: 'Insert credentials to config.json'
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)'
        fileType: 'json'
        targetFiles: |
          config.json
    - task: Docker@2
      displayName: buildAndPush
      inputs:
        containerRegistry: 'docker-hub-dheinze'
        repository: 'dheinze/predict-service'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          v0.0.$(Build.BuildId)
          latest
